version: '3.4'

services:
  mongodb_trainning:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  expressb11:
    restart: always
    image: expressb11
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
      - MONGODB_URL=${MONGODB_URL}
      - SALT_ROUND=${SALT_ROUND}
      - SECRET_JWT_KEY=${SECRET_JWT_KEY}
      - TRANSPORTER_MAIL=${TRANSPORTER_MAIL}
      - TRANSPORTER_PASS=${TRANSPORTER_PASS}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - 5000:5000
    command: npm start
    volumes:
      - .:/usr/src/app
